name: Build and test ROS packages

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: galactic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: station
          target-ros2-distro: galactic
